### ISSUE TITLE
[BUG] Verified Exporter (Writes Error Message into the XML Export)

### ISSUE THREAD

**Issue by FantasticoFox** [FantasticoFox/DataAccounting#53]
The line in question is the contains array_walk

<br/>
<b>Warning</b>
: array_flip(): Can only flip STRING and INTEGER values! in
<b>/var/www/html/extensions/ExtensionDataAccounting/includes/SpecialVerifiedExport.php</b>
on line
<b>70</b>
<br/>
<br/>
<b>Warning</b>
: array_flip(): Can only flip STRING and INTEGER values! in
<b>/var/www/html/extensions/ExtensionDataAccounting/includes/SpecialVerifiedExport.php</b>
on line
<b>70</b>
<br/>
<br/>
<b>Notice</b>
: Only variables should be passed by reference in
<b>/var/www/html/extensions/ExtensionDataAccounting/includes/SpecialVerifiedExport.php</b>
on line
<b>70</b>
<br/>

**Comment by rht** [comment]
The reason why the warning happens is probably because some of the values in the key-value pair is null. We need a way to ensure that null values either don't happen or are handled properly.

**Comment by FantasticoFox** [comment]
Could not be reproduced
