### ISSUE TITLE
Make a script to generate sample pages and DB entries

### ISSUE THREAD

**Issue by rht** [FantasticoFox/DataAccounting#66]
This is handy to test a fresh MediaWiki instances.

**Comment by FantasticoFox** [comment]
This is related to the https://github.com/FantasticoFox/PKC-content where we have all the data for auto-population of a new pkc.

**Comment by FantasticoFox** [comment]
This is part of the installation (should be options) of the micro-PKC installation https://github.com/FantasticoFox/micro-PKC

**Comment by FantasticoFox** [comment]
Done. It's a PKC issue as well. @luan solved it.
