### ISSUE TITLE
theme: Medik has an issue when user is not logged in

### ISSUE THREAD

**Issue by rht** [FantasticoFox/DataAccounting#69]
`Notice: Undefined index: login-private in /var/www/html/skins/Medik/includes/MedikTemplate.php on line 386`.

**Comment by FantasticoFox** [comment]
![image](https://user-images.githubusercontent.com/45313235/134760916-3a6e902b-9dd7-4176-b60f-1eb31c048a68.png)

**Comment by FantasticoFox** [comment]
We changed skin so it's not relevant anymore.
