### ISSUE TITLE
Make sure the Metamask network is consistent with the database network

### ISSUE THREAD

**Issue by rht** [FantasticoFox/DataAccounting#97]
This is to prevent the situation when the user accidentally publishes using mainnet instead of Goerli net.

**Comment by FantasticoFox** [comment]
Solved. Related commits:
- 0a871daf233daa5184549f708ef57a212cc3ef4e
- a69bc5f209af19142c010cb72d6c87d80aa8fd60
- 2cd001b5ce3f25b17c788df609fb49cdcdfb24c4
