### ISSUE TITLE
import: Automatically populate interwiki prefix from the domain ID of the xml file

### ISSUE THREAD

**Issue by rht** [FantasticoFox/DataAccounting#98]

**Comment by FantasticoFox** [comment]
Somebody new to the software will always miss the prefix.

**Comment by rht** [comment]
Fixed in https://github.com/FantasticoFox/DataAccounting/commit/e86507e65f1e156f4799dbba31976f7b5d108e82 and https://github.com/FantasticoFox/DataAccounting/commit/d41a23f0bf4e76b169278693132369a6302b9c0a.
